More informative error messages when the <tool>-* scripts are called from out of a docker image

diff --git a/scripts/MUST-build b/scripts/MUST-build
--- a/scripts/MUST-build
+++ b/scripts/MUST-build
@@ -1,10 +1,21 @@
 #! /bin/sh
 
-set -e # Fail on error
-
 # Go to the MBI root directory
 cd "$(dirname "$0")"/../
 rootdir=$(pwd)
+
+# Check that we have the right image
+if [ -e /MBI ] 
+then 
+   echo "This seems to be a MBI docker image. Good."
+else
+   echo "Please run this script in a MBI docker image. Run these commands:"
+   echo "  docker build -f Dockerfile -t mpi-bugs-initiative:latest . # Only the first time"
+   echo "  docker run -it --rm --name MIB --volume $(pwd):/MBI mpi-bugs-initiative /MBI/scripts/MUST-build"
+   exit 1
+fi
+
+set -e # Fail on error
 
 rm -rf /tmp/build-must ; mkdir /tmp/build-must
 cd /tmp/build-must
